<?xml version="1.0"?>
<robot name="robot_manipulator" xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:include filename="$(find robot_manipulator)/urdf/wheels.xacro"/>
	<xacro:include filename="$(find robot_manipulator)/urdf/caster_wheels.xacro"/>
	<xacro:include filename="$(find robot_manipulator)/urdf/lidar.xacro"/>

	<link name="base_footprint" />

	<joint name="base_joint" type="fixed">
    <parent link="base_footprint" />
    <child link="base_link" />
    <origin xyz="0 0 0.1" rpy="0 0 0" />
  </joint>

	<link name="base_link" >
		<visual>
			<origin rpy="0 0 0" xyz="0 0 0" />
			<geometry>
				<cylinder length="0.15" radius="0.25" />
			</geometry>
			<material name="red">
				<color rgba="0.8 0.0 0.0 1.0" />
			</material>
		</visual>
		<collision>
			<origin rpy="0 0 0" xyz="0 0 0" />
			<geometry>
				<cylinder length="0.15" radius="0.2" />
			</geometry>
		</collision>
		<inertial>
			<mass value="15.0" />
			<origin xyz="0.0 0 0.0" />
			<inertia ixx="2.3" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.5" />
		</inertial>
	</link>

	<gazebo reference="base_link">
		<selfCollide>false</selfCollide>
		<material value="Gazebo/Red"/>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

	<!-- caster wheels -->
	<xacro:caster_wheel name="back" parent="base_link" >
		<origin xyz="-0.23 0 -0.088" rpy="0 0 0" />
	</xacro:caster_wheel>
	<xacro:caster_wheel name="front" parent="base_link" >
		<origin xyz="0.23 0 -0.088" rpy="0 0 0" />
	</xacro:caster_wheel>

	<!-- wheels -->
	<xacro:wheel name="left" parent="base_link" >
		<origin xyz="0 0.2 -0.04" rpy="0 0 0" />
	</xacro:wheel>
	<xacro:wheel name="right" parent="base_link" >
		<origin xyz="0 -0.2 -0.04" rpy="0 0 0" />
	</xacro:wheel>

	<gazebo>
		<plugin name="base_diff_drive" filename="libgazebo_ros_diff_drive.so"> 
			<!-- <ros> tags are needed for nav2_gazebo_spawner -->
      <ros>
      </ros>
			<update_rate>100.0</update_rate>
			<left_joint>wheel_left_joint</left_joint>
			<right_joint>wheel_right_joint</right_joint>
			<wheel_separation>0.4</wheel_separation>
			<wheel_diameter>${2*wheel_radius}</wheel_diameter>
			<max_wheel_torque>100</max_wheel_torque>
			<max_wheel_acceleration>200</max_wheel_acceleration>
			<publish_odom>true</publish_odom>
			<publish_odom_tf>true</publish_odom_tf>
			<publish_wheel_tf>false</publish_wheel_tf>
      <odometry_topic>odom</odometry_topic>
			<odometry_frame>odom</odometry_frame>
			<robot_base_frame>base_footprint</robot_base_frame>
		</plugin>
	</gazebo>

	<!-- Sensors -->
	<xacro:lidar_sensor name="lidar" parent="base_link" >
		<origin xyz="0.2 0 0.075" rpy="0 0 0"/>
	</xacro:lidar_sensor>

</robot>